# Generated by Django 5.2.8 on 2025-11-17 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labor_rate_per_hour', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('material_markup_percentage', models.FloatField(default=30)),
                ('overhead_percentage', models.FloatField(default=15)),
                ('profit_margin_percentage', models.FloatField(default=25)),
                ('polster_fabric_base_price', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
                ('polster_labor_rate', models.DecimalField(decimal_places=2, default=65.0, max_digits=6)),
                ('foam_types', models.JSONField(blank=True, default=dict, null=True)),
                ('seam_extras', models.JSONField(blank=True, default=dict, null=True)),
                ('antirutsch_price', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('zipper_price', models.DecimalField(decimal_places=2, default=0.6, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='AccountingAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.UUIDField()),
                ('action_type', models.CharField(choices=[('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=20)),
                ('user_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['table_name', 'record_id'], name='calculator__table_n_d7c9fe_idx'), models.Index(fields=['timestamp'], name='calculator__timesta_49bbb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('datanorm_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='calculator__categor_baaddf_idx'), models.Index(fields=['datanorm_id'], name='calculator__datanor_92ca5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PricePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project_features', models.JSONField()),
                ('predicted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.FloatField()),
                ('similar_projects_count', models.IntegerField()),
                ('model_version', models.CharField(max_length=50)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('was_accepted', models.BooleanField(blank=True, null=True)),
                ('user_modified_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prediction_error', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='calculator__timesta_bdb2cb_idx'), models.Index(fields=['model_version'], name='calculator__model_v_8c5409_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_type', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('total_area_sqm', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('wood_type', models.CharField(max_length=50)),
                ('complexity', models.IntegerField(choices=[(1, 'Einfach'), (2, 'Mittel'), (3, 'Komplex')])),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_date', models.DateField()),
                ('description_embedding', models.JSONField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-project_date'],
                'indexes': [models.Index(fields=['wood_type', 'project_type'], name='calculator__wood_ty_cd2183_idx'), models.Index(fields=['project_date'], name='calculator__project_8aecdf_idx'), models.Index(fields=['is_finalized'], name='calculator__is_fina_93f9c5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('region', models.CharField(max_length=50)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='calculator.material')),
            ],
            options={
                'indexes': [models.Index(fields=['material', 'recorded_at'], name='calculator__materia_eab91d_idx'), models.Index(fields=['valid_from', 'valid_to'], name='calculator__valid_f_a988ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('image', 'Image (JPG/PNG)'), ('txt', 'Text File')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('text_preview', models.CharField(blank=True, max_length=500, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('extracted_features', models.JSONField(blank=True, null=True)),
                ('similar_projects', models.JSONField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('image_format', models.CharField(blank=True, max_length=20, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Ausstehend'), ('processing', 'Wird verarbeitet'), ('completed', 'Abgeschlossen'), ('failed', 'Fehler')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
                ('searchable_text', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='calculator.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_type'], name='calculator__file_ty_8885f1_idx'), models.Index(fields=['processing_status'], name='calculator__process_dae6f5_idx'), models.Index(fields=['project'], name='calculator__project_bb9e59_idx'), models.Index(fields=['created_at'], name='calculator__created_dba37c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='calculator.project')),
            ],
            options={
                'unique_together': {('project', 'material')},
            },
        ),
    ]
